version: "1.0"
description: "Default Linux DFIR triage configuration"
artifacts:
  - name: "syslog"
    artifact_type:
      Linux: SysLogs
    source_path: "/var/log/syslog"
    destination_name: "syslog"
    description: "System logs"
    required: true
    metadata:
      category: "logs"
      priority: "high"
  
  - name: "auth.log"
    artifact_type:
      Linux: SysLogs
    source_path: "/var/log/auth.log"
    destination_name: "auth.log"
    description: "Authentication logs"
    required: true
    metadata:
      category: "logs"
      priority: "high"
  
  - name: "journal"
    artifact_type:
      Linux: Journal
    source_path: "/var/log/journal"
    destination_name: "journal"
    description: "Systemd journal logs"
    required: false
    metadata:
      category: "logs"
      priority: "medium"
  
  - name: "proc-cmdline"
    artifact_type:
      Linux: Proc
    source_path: "/proc/cmdline"
    destination_name: "proc_cmdline"
    description: "Kernel command line"
    required: false
    metadata:
      category: "system"
      priority: "low"
  
  - name: "proc-modules"
    artifact_type:
      Linux: Proc
    source_path: "/proc/modules"
    destination_name: "proc_modules"
    description: "Loaded kernel modules"
    required: false
    metadata:
      category: "system"
      priority: "medium"
  
  - name: "audit.log"
    artifact_type:
      Linux: Audit
    source_path: "/var/log/audit/audit.log"
    destination_name: "audit.log"
    description: "Audit logs"
    required: false
    metadata:
      category: "logs"
      priority: "high"
  
  - name: "crontab"
    artifact_type:
      Linux: Cron
    source_path: "/etc/crontab"
    destination_name: "crontab"
    description: "System crontab"
    required: false
    metadata:
      category: "persistence"
      priority: "medium"
  
  - name: "cron.d"
    artifact_type:
      Linux: Cron
    source_path: "/etc/cron.d"
    destination_name: "cron.d"
    description: "System cron jobs"
    required: false
    metadata:
      category: "persistence"
      priority: "medium"
  
  - name: "bash_history"
    artifact_type:
      Linux: Bash
    source_path: "$HOME/.bash_history"
    destination_name: "bash_history"
    description: "Bash command history"
    required: false
    metadata:
      category: "user_activity"
      priority: "medium"
  
  - name: "dpkg.log"
    artifact_type:
      Linux: Dpkg
    source_path: "/var/log/dpkg.log"
    destination_name: "dpkg.log"
    description: "Package installation logs"
    required: false
    metadata:
      category: "software"
      priority: "medium"
  
  - name: "systemd-units"
    artifact_type:
      Linux: Systemd
    source_path: "/etc/systemd/system"
    destination_name: "systemd_units"
    description: "Systemd unit files"
    required: false
    metadata:
      category: "persistence"
      priority: "high"
  
  - name: "passwd"
    artifact_type:
      Linux: Systemd
    source_path: "/etc/passwd"
    destination_name: "passwd"
    description: "User accounts"
    required: true
    metadata:
      category: "users"
      priority: "high"
  
  - name: "shadow"
    artifact_type:
      Linux: Systemd
    source_path: "/etc/shadow"
    destination_name: "shadow"
    description: "Password hashes"
    required: true
    metadata:
      category: "users"
      priority: "high"
  
  - name: "ssh-config"
    artifact_type:
      Linux: Systemd
    source_path: "/etc/ssh/sshd_config"
    destination_name: "sshd_config"
    description: "SSH server configuration"
    required: false
    metadata:
      category: "configuration"
      priority: "medium"
  
  - name: "authorized_keys"
    artifact_type:
      Linux: Systemd
    source_path: "$HOME/.ssh/authorized_keys"
    destination_name: "authorized_keys"
    description: "SSH authorized keys"
    required: false
    metadata:
      category: "authentication"
      priority: "high"

global_options:
  skip_locked_files: "true"
  max_file_size_mb: "1024"
  compress_artifacts: "true"
  generate_bodyfile: "true"
  bodyfile_calculate_hash: "false"  # Optional, disabled by default
  bodyfile_hash_max_size_mb: "100"  # Skip files larger than this
  bodyfile_skip_paths: "/proc,/sys,/dev"  # Paths to skip for hashing
  bodyfile_use_iso8601: "true"  # Use ISO 8601 timestamps instead of Unix epoch
