name: RS-Collector Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }} (${{ matrix.feature_name }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false  # Continue with other builds if one fails
      matrix:
        include:
          # ==== STANDARD BUILDS ====
          
          # Linux builds
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            os_normalized: linux
            target: x86_64-unknown-linux-gnu
            features: ""
            feature_name: "standard"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
          
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            os_normalized: linux
            target: x86_64-unknown-linux-gnu
            features: "memory_collection,linux_memory"
            feature_name: "memory"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
          
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            os_normalized: linux
            target: x86_64-unknown-linux-gnu
            features: "memory_collection,linux_memory,yara"
            feature_name: "memory+yara"
            dependencies: |
              sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config libyara-dev
          
          # macOS builds
          - os: macos
            runner: macos-latest
            arch: x86_64
            os_normalized: macos
            target: x86_64-apple-darwin
            features: ""
            feature_name: "standard"
            dependencies: brew install openssl pkg-config
          
          - os: macos
            runner: macos-latest
            arch: x86_64
            os_normalized: macos
            target: x86_64-apple-darwin
            features: "memory_collection,macos_memory"
            feature_name: "memory"
            dependencies: brew install openssl pkg-config
          
          # Windows builds
          - os: windows
            runner: windows-latest
            arch: x86_64
            os_normalized: windows
            target: x86_64-pc-windows-msvc
            features: ""
            feature_name: "standard"
            dependencies: ""
          
          - os: windows
            runner: windows-latest
            arch: x86_64
            os_normalized: windows
            target: x86_64-pc-windows-msvc
            features: "memory_collection,windows_memory"
            feature_name: "memory"
            windows_memory_setup: true
            dependencies_script: |
              # Install Visual C++ Build Tools & Windows SDK components
              choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
              choco install windows-sdk-10-version-2004-all
              
              # Set environment variables for MemProcFS
              echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
              
              # Install any vcpkg dependencies if needed
              vcpkg install openssl:x64-windows

          # ==== ARM64 BUILDS ====
          
          # Linux ARM64
          - os: ubuntu
            runner: ubuntu-latest-arm64
            arch: arm64
            os_normalized: linux
            target: aarch64-unknown-linux-gnu
            features: ""
            feature_name: "standard"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
            native: true
          
          - os: ubuntu
            runner: ubuntu-latest-arm64
            arch: arm64
            os_normalized: linux
            target: aarch64-unknown-linux-gnu
            features: "memory_collection,linux_memory"
            feature_name: "memory"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
            native: true
          
          # macOS ARM64 (Apple Silicon) 
          - os: macos
            runner: macos-14
            arch: arm64
            os_normalized: macos
            target: aarch64-apple-darwin
            features: ""
            feature_name: "standard"
            dependencies: brew install openssl pkg-config
            native: true
          
          - os: macos
            runner: macos-14
            arch: arm64
            os_normalized: macos
            target: aarch64-apple-darwin
            features: "memory_collection,macos_memory"
            feature_name: "memory"
            dependencies: brew install openssl pkg-config
            native: true
          
          # Windows ARM64 (cross-compiled)
          - os: windows
            runner: windows-latest
            arch: arm64
            os_normalized: windows
            target: aarch64-pc-windows-msvc
            features: ""
            feature_name: "standard"
            dependencies: ""
            native: false
            setup_cross: |
              rustup target add aarch64-pc-windows-msvc

          # ==== EMBEDDED CONFIG BUILDS ====
          
          # Linux with embedded config
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            os_normalized: linux
            target: x86_64-unknown-linux-gnu
            features: "embed_config"
            feature_name: "embedded-config"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
            use_config_embedding: true
            artifact_name: rust_collector_linux
          
          # macOS with embedded config
          - os: macos
            runner: macos-latest
            arch: x86_64
            os_normalized: macos
            target: x86_64-apple-darwin
            features: "embed_config"
            feature_name: "embedded-config"
            dependencies: brew install openssl pkg-config
            use_config_embedding: true
            artifact_name: rust_collector_macos
          
          # Windows with embedded config
          - os: windows
            runner: windows-latest
            arch: x86_64
            os_normalized: windows
            target: x86_64-pc-windows-msvc
            features: "embed_config"
            feature_name: "embedded-config"
            dependencies: ""
            use_config_embedding: true
            artifact_name: rust_collector_windows.exe
          
          # ==== BUILDS USING NEW BUILD COMMAND ====
          
          # Linux with build command
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            os_normalized: linux
            target: x86_64-unknown-linux-gnu
            feature_name: "build-command"
            dependencies: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
            use_build_command: true
            artifact_name: rust_collector_linux_cmd
          
          # macOS with build command
          - os: macos
            runner: macos-latest
            arch: x86_64
            os_normalized: macos
            target: x86_64-apple-darwin
            feature_name: "build-command"
            dependencies: brew install openssl pkg-config
            use_build_command: true
            artifact_name: rust_collector_macos_cmd
          
          # Windows with build command
          - os: windows
            runner: windows-latest
            arch: x86_64
            os_normalized: windows
            target: x86_64-pc-windows-msvc
            feature_name: "build-command"
            dependencies: ""
            use_build_command: true
            artifact_name: rust_collector_windows_cmd.exe

    steps:
    - uses: actions/checkout@v4
      
    # Set up Rust toolchain
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
        
    # Setup cross-compilation if needed
    - name: Set up cross-compilation
      if: matrix.setup_cross != '' && matrix.native != true
      run: ${{ matrix.setup_cross }}

    # Install platform-specific dependencies
    - name: Install dependencies
      if: matrix.dependencies != ''
      run: ${{ matrix.dependencies }}

    # Windows-specific setup for memory collection
    - name: Windows memory collection setup
      if: matrix.os == 'windows' && matrix.windows_memory_setup == true
      shell: pwsh
      run: ${{ matrix.dependencies_script }}

    # Cache dependencies for faster builds
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.feature_name }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.feature_name }}-cargo-
          ${{ matrix.os }}-${{ matrix.arch }}-cargo-

    # Prepare OS-specific config for embedded config builds
    - name: Prepare OS-specific config
      if: matrix.use_config_embedding == true
      shell: bash
      run: |
        mkdir -p config/
        echo "Using OS-specific config for ${{ matrix.os_normalized }}"
        cp config/default_${{ matrix.os_normalized }}_config.yaml config/default_config.yaml
        # Also copy to OS-specific location for build.rs to find
        cp config/default_${{ matrix.os_normalized }}_config.yaml config/default_${{ matrix.os_normalized }}_config.yaml
    
    # Set environment variable for build.rs to use specific config
    - name: Set config environment variable
      if: matrix.use_config_embedding == true
      shell: bash
      run: |
        echo "RS_COLLECTOR_CONFIG=config/default_${{ matrix.os_normalized }}_config.yaml" >> $GITHUB_ENV
      
    # Build with the specified features (debug build for testing)
    - name: Debug build
      if: matrix.use_build_command != true
      run: cargo build --verbose --target ${{ matrix.target }} ${{ matrix.features != '' && format('--features={0}', matrix.features) || '' }}
      
    # Run tests (for non-cross-compiled builds)
    - name: Test
      if: matrix.native != false && matrix.use_build_command != true
      run: cargo test --verbose --target ${{ matrix.target }} ${{ matrix.features != '' && format('--features={0}', matrix.features) || '' }}
      
    # Build release version
    - name: Release build
      if: matrix.use_build_command != true
      run: cargo build --release --verbose --target ${{ matrix.target }} ${{ matrix.features != '' && format('--features={0}', matrix.features) || '' }}
    
    # Build using the new build command
    - name: Build with rs-collector build command
      if: matrix.use_build_command == true
      shell: bash
      run: |
        # First build the tool itself
        cargo build --verbose
        
        # Then use it to build the final binary with embedded config
        ./target/debug/rust_collector build -c config/default_${{ matrix.os_normalized }}_config.yaml --target-os ${{ matrix.os_normalized }} -n ${{ matrix.artifact_name }}
      
    # Upload artifacts for all builds
    - name: Upload artifacts (standard builds)
      if: matrix.use_build_command != true
      uses: actions/upload-artifact@v4
      with:
        name: rust_collector-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.feature_name }}
        path: |
          target/${{ matrix.target }}/release/rust_collector*
          !target/${{ matrix.target }}/release/rust_collector.d
          !target/${{ matrix.target }}/release/rust_collector.pdb
    
    # Upload artifacts for build command builds
    - name: Upload artifacts (build command)
      if: matrix.use_build_command == true
      uses: actions/upload-artifact@v4
      with:
        name: rust_collector-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.feature_name }}
        path: ${{ matrix.artifact_name }}
          
    # Optional: Create tagged release when tag is pushed
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ matrix.use_build_command == true && matrix.artifact_name || format('target/{0}/release/rust_collector*', matrix.target) }}
          !target/${{ matrix.target }}/release/rust_collector.d
          !target/${{ matrix.target }}/release/rust_collector.pdb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
